name: Test

on:
  workflow_dispatch: {}
  push: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]
        toolchain: [
          stable,
        ]
        nodever: [
          22
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Toolchain
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --profile minimal --no-self-update
          rustup default ${{ matrix.toolchain }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodever }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Utilities
        run: |
          cargo install cargo-sweep
          cargo install cargo-rdme
          cargo install --path rs/voidmerge --bin vm

      - name: Cargo Sweep Stamp
        run: cargo sweep --stamp

      - name: Make Test
        run: make test

      - name: Check No Change
        if: runner.os == 'Linux'
        run: git diff --exit-code

      - name: Cargo Sweep File
        run: cargo sweep --file
